[package]
name = "desec_api"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
reqwest = { version = "0.11.26", default-features = false, features = ["rustls-tls", "json"] }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
